# title: Workshop on Efficiency, Security, and Generalization of Multimedia Foundation Models
# description: ESGMFM @ ACM Multimedia 2024

markdown: kramdown

baseurl: /

show_downloads: false

theme: jekyll-theme-cayman
